version: "3.9"


x-db-environment: &x-db-environment
  POSTGRES_SSL_MODE: "disable"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "order_service"
  POSTGRES_PASSWORD: "order_service"
  POSTGRES_USER: "order_service"

x-backend-app-environment: &x-backend-app-environment
  GOMAXPROCS: "1"
  # App
  APP_NAME: "Сервис заказов"
  APP_VERSION: "1.0.0"
  # HTTP settings
  HTTP_PORT: "8080"
  # Logger
  LOG_LEVEL: "debug"
  # PG
  PG_POOL_MAX: "2"
  PG_URL: "postgres://user:myAwEsOm3pa55@w0rd@db:5432/db"
  # RMQ
  RMQ_RPC_SERVER: "rpc_server"
  RMQ_RPC_CLIENT: "rpc_client"
  RMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
  # Metrics
  METRICS_ENABLED: "true"
  # Swagger
  SWAGGER_ENABLED: "true"


services:
  db:
    container_name: order-service-db
    image: postgres:17-alpine
    environment:
      <<: *x-db-environment
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      app_network:
        aliases:
          - db.lvh.me

  # app:
  #   container_name: order-service-app
  #   platform: linux/amd64
  #   pid: "host"
  #   build:
  #     context: .
  #   environment:
  #     <<: *x-backend-app-environment
  #   ports:
  #     - "8086:8080"
  #   depends_on:
  #     - db
  #   networks:
  #     app_network:
  #       aliases:
  #         - app.lvh.me
  jaeger:
    image: jaegertracing/jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14268:14268"
    environment:
      - LOG_LEVEL=debug
    networks:
      - app_network

networks:
  app_network:
    external: false


volumes:
  postgres_data:
    driver: local
